server:
  port: 8081

spring:
  datasource:
    driver-class-name:com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/travel?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&AllowPublicKeyRetrieval=True
    username: admin
    password: 123456

  mybatis-plus:
    mapper-locations: mapper/*.xml
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      map-underscore-to-camel-case: true
    type-aliases-package: com.example.travel.entity

wx:
  appid: 123
  appsecret: 456